CREATE TABLE "igdb_cache" (
    "slug" TEXT NOT NULL PRIMARY KEY,
    "data" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP
);
