services:
  - type: web
    name: community
    env: node
    plan: free
    buildCommand: npm ci --production=false && npm run build && npx prisma migrate deploy && npm prune --production
    startCommand: npm run start
    healthCheckPath: /healthcheck
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV #required so NODE_ENV is set in build env
        value: production
