mutation(
  $type: StructureType!
  $name: String!
  $about: String!
  $country: String!
  $city: String!
) {
  createStructure(
    type: $type
    name: $name
    about: $about
    location: {
      country: $country
      city: $city
    }
  ) {
    type
    name
    about
    location {
      country
      city
    }
  }
}