query entity($id: UUID!) {
  entity(id: $id) {
    id
    type
    name
    about
    createdAt
    
    location {
      latitude
      longitude
    }

    people {
      totalCount
    }

    games {
      totalCount
    }

    events {
      totalCount
    }
  }
}
