query entities {
  entities {
    totalCount
    nodes {
      id
      type
      name
      about

      location {
        city
        country
        latitude
        longitude
      }

      people {
        totalCount
      }

      images {
        totalCount
      }

      events {
        totalCount
      }
    }
  }
}