query getEvent($id: ID!) {
  event(id: $id) {
    id
    name
    about
    startAt
    endAt
    location {
      city
      country
    }
    images {
      id
      mimetype
    }
    structures {
      id
      name
    }
  }
}
