{
  games(last: 5, orderBy: CREATED_AT_DESC) {
    nodes {
      id
      name
      images {
        nodes {
          id
          imageFile
        }
      }
    }
  }

  entities(last: 10, orderBy: CREATED_AT_DESC) {
    nodes {
      id
      name
      type
      people {
        totalCount
      }
      games {
        totalCount
      }
    }
  }

  events(last: 10, orderBy: STARTS_AT_DESC) {
    nodes {
      id
      name
      startsAt
      endsAt
      entities {
        totalCount
      }
      games {
        totalCount
      }
      location {
        countryCode
        city
      }
    }
  }
}
