name: Client CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install & build
      working-directory: ./client
      run: |
        npm install -g npm@latest
        npm ci
        npm run build
      env:
        CI: true
    - name: SSH Deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
      with:
        args: ./deploy_client.sh
